### PR TITLE
fix(authheader): Invalid token

### PR DESCRIPTION
**Pull request by wpacks**
Fixed the token error

### CODE REVIEW

**Comment by bcomnes** [comment]
Cool!  Thanks for the fix.  Looks like there are a couple code style violations that still need fixing in this PR.  Can you fix those up?

**Comment by wpacks** [comment]
Hi Bret, there is anothet bug when i tried this module on expressjs post. I
dont know why it took a lot of time to get the token. I will fix that when
having free time.

Vào Chủ Nhật, ngày 25 tháng 10 năm 2015, Bret Comnes <
notifications@github.com> đã viết:

> Cool! Thanks for the fix. Looks like there are a couple code style
> violations that still need fixing in this PR. Can you fix those up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcomnes/node-bearer-token/pull/1#issuecomment-150839685>
> .
>


-- 
Trương Thanh Sang

Mobile: 0989 895 409

**Comment by bcomnes** [comment]
I haven't extensively tested with express yet.  This module was part of a bigger plan that hasn't been realized yet.  I appreciate any input and contributions that you find/contribute.

**Comment by wpacks** [comment]
How could we fix that error on travis: 

/home/travis/build/bcomnes/node-bearer-/home/travis/build/bcomnes/node-bearer-token/test/authBody.js:53:2: Block must not be padded by blank lines.
  /home/travis/build/bcomnes/node-bearer-token/test/authHeader.js:53:2: Block must not be padded by blank lines.
  /home/travis/build/bcomnes/node-bearer-token/test/index.js:51:2: Block must not be padded by blank lines.
  /home/travis/build/bcomnes/node-bearer-token/test/index.js:107:2: Block must not be padded by blank lines.

**Comment by bcomnes** [comment]
The code is checked by http://standardjs.com/ which enforces code style consistency.  Each line specifies a file and a style violation that needs a minor tweak.

**Comment by bcomnes** [comment]
Ok merged!  I also added a conditional to check if the body had already been parsed by express to avoid extra work.

**Comment by wpacks** [comment]
Cheers.

Vào Thứ Sáu, ngày 30 tháng 10 năm 2015, Bret Comnes <
notifications@github.com> đã viết:

> Ok merged! I also added a conditional to check if the body had already
> been parsed by express to avoid extra work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcomnes/node-bearer-token/pull/1#issuecomment-152402698>
> .
>


-- 
Trương Thanh Sang

Mobile: 0989 895 409

**Pull request merged**
